name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            enhancement
            feature
            feat
            bug
            refactoring
            bugfix
            fix
            build
            ci
            testing
            test
            chore
            refactor
            perf
            BREAKING CHANGE
            documentation
            breaking
            docs
            dependencies
          requireScope: false
          wip: false
          validateSingleCommit: true